version: "1"

services:
  # ---------------- Single Web Service (API + Frontend) ----------------
  - type: web
    name: biller-np48
    runtime: node
    plan: free
    region: oregon
    healthCheckPath: /
    buildCommand: |
      cd backend && npm install
      cd ../frontend && npm install && npm run build
    startCommand: node backend/server.js
    autoDeployTrigger: commit
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_EXPIRE
        value: 7d
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false